#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1

# Joint trajectory controller
position_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_pan
    - joint_tilt

  state_publish_rate: 1 # Defaults to 50
  action_monitor_rate: 20 # Defaults to 20
